apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: django
  name: django
spec:
  runPolicy: Serial
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.5'
        namespace: openshift
  source:
    git:
      ref: master
      uri: 'https://github.com/openshift/django-ex.git'
    type: Git

  output:
    to:
      kind: ImageStreamTag
      name: 'django:latest'
